### ISSUE TITLE
DNS resolution failing for sqlalchemy.org

### ISSUE THREAD

**Issue by jayhale** [zzzeek/redirectthedocs#1]
DNS resolution is failing for `www.sqlalchemy.org` when attempting to access docs.

First issue: Hope you're able to get DNS working quickly again.

Second issue: Are you willing to clone the documentation on https://readthedocs.org?  Would be nice to have another option for viewing the rendered docs without having to build them locally from source.

**Comment by jayhale** [comment]
Just realized this is a general repo - following links too fast - apologies.

**Comment by zzzeek** [comment]
> DNS resolution is failing for `www.sqlalchemy.org` when attempting to access docs.

seems fine to me

```
> server ns1.linode.com
Default server: ns1.linode.com
Address: 162.159.27.72#53
Default server: ns1.linode.com
Address: 2400:cb00:2049:1::a29f:1a63#53
> www.sqlalchemy.org
Server:		ns1.linode.com
Address:	162.159.27.72#53

www.sqlalchemy.org	canonical name = ln.sqlalchemy.org.
ln.sqlalchemy.org	canonical name = ln.zzzcomputing.com.
ln.zzzcomputing.com	canonical name = ln5.zzzcomputing.com.
Name:	ln5.zzzcomputing.com
Address: 172.104.15.205

```

I don't see any gap in traffic that would indicate an outage.

everything is green on linode status: https://status.linode.com/, no incidents reported.




> 
> First issue: Hope you're able to get DNS working quickly again.
> 
> Second issue: Are you willing to clone the documentation on https://readthedocs.org? 

sqlalchemy used to have its docs on this service however we prefer to host it ourselves, as RTD was not able to reliably build our documentation and also was unable to respond to issues or provide much assistance.   The ad revenue from SQLAlchemy's docs now pay for all our hosting which is a much better use than giving it all to a third party that provides unreliable service.

> Would be nice to have another option for viewing the rendered docs without having to build them locally from source.

SQLAlhcemy's docs are always available for the last several major versions at:

http://docs.sqlalchemy.org

Also this issue tracker is for a little tool I wrote to help projects migrate from RTD, since RTD continues AFAIK to not be able to  provide a simple redirection utility even though this has been requested for many years.
